### ISSUE TITLE
Does it make sense to retire this repo (by deleting it?)

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/TwitterBot#7]
There haven't been much work on this for a while. Unless we're looking to repurpose the twitterbot for a different purpose.

**Comment by CristinaSolana** [comment]
It sure would be nice if there was an archive feature of some kind. I hate to just delete anything that someone worked on. Just thinking out loud, maybe create a separate account for retired projects?

**Comment by ErnieAtLYD** [comment]
Maybe zipping it up and uploading it to a slack channel?

**Comment by CristinaSolana** [comment]
HM. Any downside to that like space limit?

**Comment by ErnieAtLYD** [comment]
There's a 5GB file storage limit on Slack.

**Comment by CristinaSolana** [comment]
I created a free dropbox account, let's use that until we figure out a better approach. Will share creds with you.
